### ISSUE TITLE
mvn build failure

### ISSUE THREAD

**Issue by wyu** [PathwayAndDataAnalysis/causalpath#8]
Thanks for this wonderful tool. I'm trying to set it up on our local Redhat 6 server. However the jar compilation is giving me troubles.

mvn clean install

[INFO] Building causalpath 1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.panda:utility:jar:1.2.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.panda:resource:jar:1.2.1-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.482s
[INFO] Finished at: Sat Sep 04 18:44:27 EDT 2021
[INFO] Final Memory: 13M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project causalpath: Could not resolve dependencies for project org.panda:causalpath:jar:1.2.1-SNAPSHOT: The following artifacts could not be resolved: org.panda:utility:jar:1.2.1-SNAPSHOT, org.panda:resource:jar:1.2.1-SNAPSHOT: Failure to find org.panda:utility:jar:1.2.1-SNAPSHOT in https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of panda has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Change the versions of the artifact to 1.2.0-SHAPSHOT for the following dependecies to match the settings in the resource project seems to fix this error.

<dependency>
                        <groupId>org.panda</groupId>
                        <artifactId>utility</artifactId>
                        <version>1.2.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                        <groupId>org.panda</groupId>
                        <artifactId>resource</artifactId>
                        <version>1.2.0</version>
                </dependency>

However, more errors on the build again.

[INFO] Building causalpath 1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ causalpath ---
[INFO] Deleting /rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/target
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ causalpath ---
[debug] execute contextualize
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ causalpath ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 62 source files to /rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/data/SiteModProteinData.java:[3
,36] error: cannot find symbol
[ERROR]  package org.panda.resource.siteeffect
/rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/data/SiteModProteinData.java:[19,11] er
ror: cannot find symbol
[ERROR]  class SiteModProteinData
/rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/data/SiteModProteinData.java:[25,63] er
ror: cannot find symbol
[ERROR]  class SiteModProteinData
/rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/data/SiteModProteinData.java:[74,8] err
or: cannot find symbol
[ERROR]  class SiteModProteinData
/rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/resource/NetworkLoader.java:[12,30] err
or: cannot find symbol
[ERROR]  package org.panda.utility.graph
/rbxdata1/apps/pipeline/contrib/CausalPath/causalpath-master/src/main/java/org/panda/causalpath/resource/NetworkLoader.java:[286,38] er
ror: cannot find symbol
......

Thanks!
Wen

**Comment by ozgunbabur** [comment]
Hi Wen,

It should be fixed now. Please try again and let me know.

Ozgun

**Comment by wyu** [comment]
Thanks for your quick response! I updated the repo and run the install again. Looks like the error is still there.

/rbxdata1/apps/contrib/Apache/apache-maven-3.0.5/bin/mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building causalpath 1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.panda:utility:jar:1.2.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.panda:resource:jar:1.2.1-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.369s
[INFO] Finished at: Sat Sep 04 20:56:19 EDT 2021
[INFO] Final Memory: 13M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project causalpath: Could not resolve dependencies for project org.panda:causalpath:jar:1.2.1-SNAPSHOT: The following artifacts could not be resolved: org.panda:utility:jar:1.2.1-SNAPSHOT, org.panda:resource:jar:1.2.1-SNAPSHOT: Failure to find org.panda:utility:jar:1.2.1-SNAPSHOT in https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of panda has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ozgunbabur** [comment]
Please try again. Often, Maven caches contents of the remote repositories, and it does not notice the updates unless some significant amount of time passed.

**Comment by wyu** [comment]
You're exactly right! Everything is good now. Thanks!

On a related note, I'm also trying to setup the webserver for the CausalPath, should I copy the jar file built here to the "causalpath-webserver/jar" folder?

Wen

**Comment by ozgunbabur** [comment]
Glad it worked!

Setting up the webserver is a bigger adventure than building the main
project. It is currently running on Google Cloud and we haven't tested it
on different platforms. But yes, you are supposed to put the causalpath.jar
under the jar folder. Good luck with it!
